#!/bin/bash
jupyter nbextension      enable --py --sys-prefix appmode
jupyter serverextension  enable --py --sys-prefix appmode
jupyter nbextension      enable --py widgetsnbextension
jupyter-nbextension      enable --py --sys-prefix nglview 
